version: '3.8'
services: 
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - ./service/mysql:/var/lib/mysql
      - ./service/mysql/conf/my.cnf:/etc/my.cnf
      - ./service/mysql/init:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - 6380:6379
    volumes: 
      - ./service/redis/data:/data
      - ./service/redis/log:/log
      - ./service/redis/conf/redis.conf:/etc/redis/redis.conf